apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: brick
  namespace: wall
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brick
    matchExpressions:
      - {key: app, operator: In, values: [brick]}
  template:
    metadata:
      labels:
        app: brick
    spec:
      containers:
      - name: brick
        image: andrewmyhre/brick
        ports:
        - containerPort: 80
