apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: brick
  namespace: wall
  app: wall
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wall
      tier: brick
    matchExpressions:
      - {key: tier, operator: In, values: [brick]}
  template:
    metadata:
      labels:
        app: wall
        tier: brick
    spec:
      containers:
      - name: brick
        image: andrewmyhre/brick
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: brick
spec:
  type: LoadBalancer
  selector:
    app: wall
    tier: brick
  ports:
  - port: 80
    targetPort: 80
