apiVersion: v1
kind: Service
metadata:
  name: wall-mysql
  labels:
    app: wall
spec:
  ports:
    - port: 3306
  selector:
    app: wall
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wall
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wall-mysql
  labels:
    app: wall
spec:
  selector:
    matchLabels:
      app: wall
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wall
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: diddle
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim