FROM golang:alpine

RUN apk add --update --no-cache gcc libc-dev mesa-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev alpine-sdk  cmake musl-dev git mercurial

RUN mkdir /home/git; \
    cd /home/git; \
    sudo git clone https://github.com/assimp/assimp.git -b master; 

RUN cd /home/git/assimp; \
    cmake CMakeLists.txt -G 'Unix Makefiles'; \
    make; \
    make install; 
    #ldconfig;

 RUN assimp help
